#networks:
  #dem:
services:
  #pythonapp:
    
    #build: 
      #context: .
      #dockerfile: dockerfile_python
    #depends_on:
      #- database
    #networks:
      #- dem

  database:
    image: postgres:latest
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cabinet

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - 5432:5432

    #networks:
      #- dem

